[Lction 3][Homework] Выполнение домашнего задания к уроку 3
Kukamunga13/AQA_JS_Arsenov_git_hw pull request #1
Opened 2024-05-25 00:55 UTC by Kukamunga13

1. Выполнил задание 1 к уроку 3 в файле task_one.js
2. Выполнил задание 2  к уроку 3 в файле task_two.js
3. Выполнил задание 3  к уроку 3 в файле task_three.js

2024-05-25 01:18 UTC, anatoly-karpovich requested changes

2024-05-25 01:18 UTC, anatoly-karpovich commented on lesson_three_hw/task_three.js
> +if (numberEnteredByTheUser > 0) {
Please provide checks for string values that will return NaN

2024-05-25 06:39 UTC, VladimirLQA approved these changes

2024-05-26 19:43 UTC, anatoly-karpovich approved these changes

2024-05-26 19:47 UTC, merged